language: python

matrix:
    include:
        - python: 3.5
    exclude:
        - python: 2.7

install:
   - pip install nose
   - pip install coverage

before_script:
   - mkdir -p shippable/testresults/
   - mkdir -p shippable/codecoverage/

script:
    - python setup.py nosetests
